server:
  port: 8085

spring:
  application:
    name: committee-service
  datasource:

    url: jdbc:postgresql://localhost:5433/committee-service
    username: 'postgres'
    password: 'admin'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'


management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8020/eureka/
    registerWithEureka: true
    fetchRegistry: true
#  instance:
#    instanceId: '${spring.application.name}:${spring.application.instance_id:${random.value}}'
#    statusPageUrlPath: /actuator/info
#    healthCheckUrlPath: /actuator/health
#    preferIpAddress: true
#    hostname: localhost

