server:
  port: 8761

spring:
  application:
    name: discovery-server
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  instance:
        hostname: localhost
        prefer-ip-address: true
logging:
  level.com.discovery: WARN
