server:
  port: 0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      routes:
        - id: vets-service
          uri: lb://tenderer-service
          predicates:
            - Path=/api/tenderer/**
          filters:
            - StripPrefix=2
        - id: tenderee-service
          uri: lb://tenderee-service
          predicates:
            - Path=/api/tenderee/**
          filters:
            - StripPrefix=2
        - id: evaluator-service
          uri: lb://evaluator-service
          predicates:
            - Path=/api/evaluator/**
          filters:
            - StripPrefix=2
        - id: committee-service
          uri: lb://committee-service
          predicates:
            - Path=/api/committee/**
          filters:
            - StripPrefix=2
        - id: account-ws
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=2



---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http/config-server:8888