server:
  port: 0
#  port: 8081
  servlet:
    context-path: /tender

spring:
  application:
    name: evaluator-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5433/tender-db
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  #     driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'

  # JPA and Hibernate #####
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: create-drop
        show_sql: true
        format_sql: true


  output:
    ansi:
      enabled: detect

#
logging:
  level:
    org.hibernate: info
    org.springframework.web: debug



management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8020/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: '${spring.application.name}:${spring.application.instance_id:${random.value}}'
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    preferIpAddress: true
    hostname: localhost

