server:
  port: 9090

spring:
  application:
    name: user-service

  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/user-service
    password: 'admin'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
