server:
  port: 0

spring:
  application:
    name: tenderee-service
  #
  datasource:
    url: jdbc:postgresql://localhost:5433/tenderee-service
    username: 'postgres'
    password: 'admin'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  #
  devtools:
    restart:
      enabled: 'true'
  #
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'


#
management:
  endpoints:
    web:
      exposure:
        include: '*'

# eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: '${spring.application.name}:${spring.application.instance_id:${random.value}}'
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    preferIpAddress: true
    hostname: localhost


