# application.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true


spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false