server:
  port: 0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      routes:
        - id: users-status-check
          uri: lb://account-service
          predicates:
            - Path=/api/users
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/account-service/api/users, /api/users

#      routes:
#        - id: committee
#          uri: lb://COMMITTEE
#          predicates:
#            - Path=/api/committee/**

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8020/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: '${spring.application.name}:${spring.application.instance_id:${random.value}}'
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    preferIpAddress: true
    hostname: localhost

