server:
  port: 8086

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: committee
          uri: lb://COMMITTEE
          predicates:
            - Path=/api/committee/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true