spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GezahegnTsegaye/tender-system-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          refresh-rate: 60

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
  health:
    config:
      enabled: true