server:
  port: 8081

spring:
  application:
    name: tenderee-service
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/tenderee-service
    password: 'admin'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'

